const APP_NAME = 'SCH Tools | ';

const toolcategories = [
  {
    id: "schema",
    category: "Schema",
    url: "#",
    tools: [
      {
        id: "so",
        name: "Organization Schema",
        description: "An organization such as a school, NGO, corporation, club, etc. This schema is used to define the organization. This tool will help you define your organization easily in a simple visual way.",
        icon: "",
        url: "/schemas/organization",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: true,
        failed: false,
        ribbonposition: "top-right",
        ribbonclass: "popular",
      },
      {
        id: "sp",
        name: "Person Schema",
        description: "A person (alive, dead, undead, or fictional).",
        icon: "",
        url: "/schemas/person",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "ss",
        name: "Store Schema",
        description: "",
        icon: "",
        url: "/schemas/store",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "spp",
        name: "Product Schema",
        description: "Any offered product or service. For example: a pair of shoes; a concert ticket; the rental of a car; a haircut; or an episode of a TV show streamed online.",
        icon: "",
        url: "/schemas/product",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "sart",
        name: "Article or Blog Schema",
        description: "",
        icon: "",
        url: "/schemas/articleorblog",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "sb",
        name: "Book Schema",
        description: "",
        icon: "",
        url: "/schemas/book",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "swp",
        name: "Webpage Schema",
        description: "",
        icon: "",
        url: "/schemas/webpage",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "sg",
        name: "Graph Schema",
        description: "",
        icon: "",
        url: "/schemas/graph",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "se",
        name: "Event Schema",
        description: "An event happening at a certain time and location, such as a concert, lecture, or festival. Ticketing information may be added via the offers property. Repeated events may be structured as separate Event objects.",
        icon: "",
        url: "/schemas/event",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "sm",
        name: "Medical Entity Schema",
        description: "The most generic type of entity related to health and the practice of medicine.",
        icon: "",
        url: "/schemas/medicalentity",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "splace",
        name: "Place Schema",
        description: "Entities that have a somewhat fixed, physical extension.",
        icon: "",
        url: "/schemas/place",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "st",
        name: "Taxon Schema",
        description: "A set of organisms asserted to represent a natural cohesive biological unit.",
        icon: "",
        url: "/schemas/taxon",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "sintangile",
        name: "Intangible Schema",
        description: "A utility class that serves as the umbrella for a number of 'intangible' things such as quantities, structured values, etc.",
        icon: "",
        url: "/schemas/event",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "sbc",
        name: "BioChem Industry Schema",
        description: "Any biological, chemical, or biochemical thing. For example: a protein; a gene; a chemical; a synthetic chemical.",
        icon: "",
        url: "/schemas/biochemindustry",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "scw",
        name: "Creative Work Schema",
        description: "The most generic kind of creative work, including books, movies, photographs, software programs, etc.",
        icon: "",
        url: "/schemas/creativework",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
      {
        id: "saction",
        name: "Action Schema",
        description: "An action performed by a direct agent and indirect participants upon a direct object. Optionally happens at a location with the help of an inanimate instrument. The execution of the action may produce a result. Specific action sub-type documentation specifies the exact expectation of each argument/role.",
        icon: "",
        url: "/schemas/action",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "new",
      },
    ]
  },
  {
    id: "seo",
    category: "SEO",
    url: "#",
    tools: [
      {
        id: "kwr",
        name: "Keywords Research",
        description: "Keyword research is the process of finding the most important keywords for your website. This tool will guide you on how to get the keywords.",
        icon: "fa fa-database",
        url: "/keywords/research",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "popular",
      },
      {
        id: "kwm",
        name: "Keywords Maker",
        description: "Keyword maker is a tool that helps you create keywords for your website. It will help you to find the most important keywords for your website.",
        icon: "",
        url: "/keywords/keywordmaker",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: true,
        failed: false,
        ribbonposition: "top-right",
        ribbonclass: "best",
      },
    ]
  },
  {
    id: "backlinks",
    category: "Backlinks",
    url: "#",
    tools: []
  },
  {
    id: "blogs",
    category: "Blogs",
    url: "#",
    tools: [],
  },
  {
    id: "sitemaps",
    category: "Sitemaps",
    url: "/sitemaps/sitemap",
    tools: [
      {
        id: "smg",
        name: "Sitemap Generator",
        description: "Sitemap generator is a tool that helps you to create a sitemap for your website. It will generate the xml sitemap required by crawlers to help them crawl your site quickly and easily.",
        url: "/sitemaps/sitemap",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: true,
        ribbonposition: "bottom-left",
        ribbonclass: "failed"
      },
    ],
  },
  {
    id: "social",
    category: "Social",
    url: "#",
    tools: [
      {
        id: "sytc",
        name: "Youtube Chapters",
        description: "Youtube chapters helps you create video chapters quickly and easily. It is a simple tool to use and will save you alot of time.",
        icon: "",
        url: "/social/youtube/videochapters",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: true,
        failed: false,
        ribbonposition: "top-right",
        ribbonclass: "popular"
      },
      {
        id: "sytd",
        name: "YT Video Description",
        description: "Youtube chapters helps you create video chapters quickly and easily. It is a simple tool to use and will save you alot of time.",
        icon: "",
        url: "/social/youtube/videodescription",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: true,
        failed: false,
        ribbonposition: "top-right",
        ribbonclass: "popular"
      },
      {
        id: "sytsociallinks",
        name: "Add Social Links",
        description: "Add your social links in groups in order to link them easily when creating content to share or when creating your YouTube video description.",
        icon: "",
        url: "/social/links/addlinks",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: true,
        failed: false,
        ribbonposition: "top-right",
        ribbonclass: "popular"
      },
      {
        id: "sytvideoediting",
        name: "Bulk Video Editing",
        description: "Add your social links in groups in order to link them easily when creating content to share or when creating your YouTube video description.",
        icon: "",
        url: "/social/links/addlinks",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "top-right",
        ribbonclass: "popular"
      },
      {
        id: "sfb",
        name: "Content Share",
        description: "Facebook is a social networking service where users can post and share stories, images, videos, and links.",
        icon: "",
        url: "/social/facebook/facebook",
        type: "link",
        image: "/assets/images/kwrt.png",
        isActive: false,
        failed: false,
        ribbonposition: "bottom-right",
        ribbonclass: "liked"
      },
    ],
  }

]

export default toolcategories;
export { APP_NAME };